sirubo: rename funcs, reorganize args and vars

diff --git a/sirubo b/sirubo
--- a/sirubo
+++ b/sirubo
@@ -1,48 +1,43 @@
-#!/bin/sh
+#!/bin/sh -ue
+
+umask u=rw,go=
+
+list_asn=
+list_prefixes_ipv4=
+list_prefixes_ipv6=
+name_program="sirubo"
+name_os="$(uname -s)"
+whoisdomain="whois.radb.net"  # WHOIS domain to query for ASN prefixes.
+
+if [ "$name_os" = "OpenBSD" ]
+then
+	fpath_conf="/etc/$name_program.conf"
+	fpath_ruleset="/etc/pf.$name_program.conf"
+fi
+
+if [ "$name_os" = "Linux" ]
+then
+	fpath_conf="/usr/local/etc/$name_program.conf"
+	fpath_ruleset="/usr/local/etc/$name_program.ruleset"
+	fname_service="$name_program.service"
+fi
 
 main()
 {
-	# = VARS =>
-
-	set -u
-	set -e
-	umask u=rw,go=
-
-	list_asn=
-	list_prefixes_ipv4=
-	list_prefixes_ipv6=
-	name_program="sirubo"
-	whoisdomain="whois.radb.net"  # WHOIS domain to query for ASN prefixes.
-
-	if [ "$(uname -s)" = "OpenBSD" ]
+	if [ "$*" = "" ] || [ "$*" = "help" ] || [ "$*" = "-h" ]
 	then
-		fpath_conf="/etc/$name_program.conf"
-		fpath_ruleset="/etc/pf.$name_program.conf"
+		usage
 	fi
 
-	if [ "$(uname -s)" = "Linux" ]
+	if ! confirm_root
 	then
-		fpath_conf="/usr/local/etc/$name_program.conf"
-		fpath_ruleset="/usr/local/etc/$name_program.ruleset"
-		fname_service="$name_program.service"
-	fi
-
-	# = ARGS =>
-
-	if [ "$*" = "" ]
-	then
-		print_help
-		exit 1
-	fi
-
-	if [ "$*" = "help" ]
-	then
-		print_help
 		exit 1
 	fi
 	
-	confirm_root_access                 || exit $?
-	confirm_prerequisites "$fpath_conf" || exit $?
+	if ! confirm_prereqs "$fpath_conf"
+	then
+		exit 1
+	fi
 
 	if [ "$*" = "create" ]
 	then
@@ -52,7 +47,7 @@ main()
 
 		# Create Firewall Ruleset Configuration File:
 
-		if [ "$(uname -s)" = "OpenBSD" ]
+		if [ "$name_os" = "OpenBSD" ]
 		then
 			# Create Anchor in pf.conf:
 
@@ -68,7 +63,11 @@ main()
 
 			# Perform WHOIS Query of ASN(s) for Prefixes:
 
-			confirm_network_connection "$whoisdomain"
+			if ! confirm_network_connection "$whoisdomain"
+			then
+				exit 1
+			fi
+
 			confirm_asn "$whoisdomain" "$list_asn"
 
 			list_prefixes_ipv4="$(print_prefixes_ipv4 "$whoisdomain" "$list_asn")"
@@ -77,7 +76,7 @@ main()
 			if [ -z "$list_prefixes_ipv4" ] && [ -z "$list_prefixes_ipv6" ]
 			then
 				>&2 printf "> error: ASN queries did not return any prefix results.\n"
-				exit 2
+				exit 1
 			fi
 
 			# Add Rules to Reject ASN Prefixes:
@@ -115,7 +114,7 @@ main()
 			pfctl -a "$name_program" -f "$fpath_ruleset"
 		fi
 
-		if [ "$(uname -s)" = "Linux" ]
+		if [ "$name_os" = "Linux" ]
 		then
 			# Create Ruleset:
 
@@ -131,7 +130,12 @@ main()
 
 			# Perform WHOIS Query of ASN(s) for Prefixes:
 
-			confirm_network_connection "$whoisdomain"
+
+			if ! confirm_network_connection "$whoisdomain"
+			then
+				exit 1
+			fi
+
 			confirm_asn "$whoisdomain" "$list_asn"
 
 			list_prefixes_ipv4="$(print_prefixes_ipv4 "$whoisdomain" "$list_asn")"
@@ -140,7 +144,7 @@ main()
 			if [ -z "$list_prefixes_ipv4" ] && [ -z "$list_prefixes_ipv6" ]
 			then
 				>&2 printf "> error: ASN queries did not return any prefix results.\n"
-				exit 2
+				exit 1
 			fi
 
 			# Add Rules to Reject ASN Prefixes:
@@ -183,13 +187,13 @@ main()
 
 	if [ "$*" = "resume" ]
 	then
-		if [ "$(uname -s)" = "OpenBSD" ]
+		if [ "$name_os" = "OpenBSD" ]
 		then
 			rcctl enable "$name_program"
 			pfctl -a "$name_program" -f "$fpath_ruleset"
 		fi
 
-		if [ "$(uname -s)" = "Linux" ]
+		if [ "$name_os" = "Linux" ]
 		then
 			systemctl -q enable "$fname_service"
 			nft -f "$fpath_ruleset"
@@ -200,13 +204,13 @@ main()
 
 	if [ "$*" = "stop" ]
 	then
-		if [ "$(uname -s)" = "OpenBSD" ]
+		if [ "$name_os" = "OpenBSD" ]
 		then
 			rcctl disable "$name_program"
 			pfctl -a "$name_program" -F rules 2> /dev/null
 		fi
 
-		if [ "$(uname -s)" = "Linux" ]
+		if [ "$name_os" = "Linux" ]
 		then
 			systemctl -q disable "$fname_service"
 			nft delete table inet "$name_program" 2> /dev/null
@@ -241,14 +245,14 @@ confirm_network_connection()
 
 	if nc -w 1 "$whoisdomain" 43 > /dev/null 2>&1
 	then
-		return
+		return 0
 	else
 		>&2 printf "> error: Host \"%s\" unable to receive WHOIS requests or offline.\n" "$whoisdomain"
-		exit 2
+		return 1
 	fi
 }
 
-confirm_prerequisites()
+confirm_prereqs()
 {
 	fpath_conf="$1"
 
@@ -264,56 +268,58 @@ confirm_prerequisites()
 	if ! grep -Eqo "^AS[^ ]+" "$fpath_conf"
 	then
 		>&2 printf "> error: Configuration file (%s) does not contain at least one ASN. Specify before continuing.\n" "$fpath_conf"
-		return 2
+		return 1
 	fi
 
-	if [ "$(uname -s)" = "OpenBSD" ]
+	if [ "$name_os" = "OpenBSD" ]
 	then
 		if ! which pfctl > /dev/null 2>&1
 		then
 			>&2 printf "> error: \"pfctl\" is a prerequisite and was not found.\n"
-			return 2
+			return 1
 		fi
 
 		if ! which whois > /dev/null 2>&1
 		then
 			>&2 printf "> error: \"whois\" is a prerequisite and was not found.\n"
-			return 2
+			return 1
 		fi
 	fi
 
-	if [ "$(uname -s)" = "Linux" ]
+	if [ "$name_os" = "Linux" ]
 	then
 
 		if ! [ -d "/run/systemd/system" ]
 		then
 			>&2 printf "> error: \"systemd\" is a prerequisite and was not found.\n"
-			return 2
+			return 1
 		fi
 
 		if ! which nft > /dev/null 2>&1
 		then
 			>&2 printf "> error: \"nft\" is a prerequisite and was not found.\n"
-			return 2
+			return 1
 		fi
 
 		if ! which whois > /dev/null 2>&1
 		then
 			>&2 printf "> error: \"whois\" is a prerequisite and was not found.\n"
-			return 2
+			return 1
 		fi
 	fi
 
 	return 0
 }
 
-confirm_root_access()
+confirm_root()
 {
 	if [ "$(id -u)" != 0 ]
 	then
-		>&2 printf "> error: %s not running as root.\n" "$(basename "$0")"
-		return 2
+		>&2 printf "> error: Not running as root.\n"
+		return 1
 	fi
+
+	return 0
 }
 
 print_prefixes_ipv4()
@@ -338,7 +344,7 @@ print_prefixes_ipv6()
 	done
 }
 
-print_help()
+usage()
 {
 	cat <<EOF
 Usage: $(basename "$0") [command]
@@ -348,6 +354,8 @@ Usage: $(basename "$0") [command]
   stop      Undo firewall reject rules.
   resume    Resume enforcement of cached firewall reject rules.
 EOF
+
+	exit 1
 }
 
 print_linux_systemd_service_file()
