sirubo: don't use variables inside printf strings

diff --git a/sirubo b/sirubo
--- a/sirubo
+++ b/sirubo
@@ -58,7 +58,7 @@ main()
 
 			if ! cat "/etc/pf.conf" | grep -Eq "^anchor $name_program$"
 			then
-				printf "anchor $name_program" >> "/etc/pf.conf"
+				printf "anchor %s" "$name_program" >> "/etc/pf.conf"
 			fi
 
 			# Create Ruleset:
@@ -84,17 +84,17 @@ main()
 			
 			if ! [ -z "$list_prefixes_ipv4" ]
 			then
-				printf "$list_prefixes_ipv4\n" | while IFS= read -r prefix
+				printf "%s\n" "$list_prefixes_ipv4" | while IFS= read -r prefix
 				do
-					printf "block return on any inet from any to $prefix\n" >> "$fpath_ruleset.tmp"
+					printf "block return on any inet from any to %s\n" "$prefix" >> "$fpath_ruleset.tmp"
 				done
 			fi
 
 			if ! [ -z "$list_prefixes_ipv6" ]
 			then
-				printf "$list_prefixes_ipv6\n" | while IFS= read -r prefix
+				printf "%s\n" "$list_prefixes_ipv6" | while IFS= read -r prefix
 				do
-					printf "block return on any inet6 from any to $prefix\n" >> "$fpath_ruleset.tmp"
+					printf "block return on any inet6 from any to %s\n" "$prefix" >> "$fpath_ruleset.tmp"
 				done
 			fi
 
@@ -122,10 +122,10 @@ main()
 			test -f "$fpath_ruleset.tmp" && rm -f "$fpath_ruleset.tmp"
 			touch "$fpath_ruleset.tmp"
 
-			printf "#!/usr/sbin/nft -f\n\n"                                                                               >> "$fpath_ruleset.tmp"
-			printf "add table inet $name_program\n"                                                                       >> "$fpath_ruleset.tmp"
-			printf "flush table inet $name_program\n"                                                                     >> "$fpath_ruleset.tmp"
-			printf "add chain inet $name_program $name_program { type filter hook output priority 0 ; policy accept; }\n" >> "$fpath_ruleset.tmp"
+			printf "#!/usr/sbin/nft -f\n\n"                                                                                         >> "$fpath_ruleset.tmp"
+			printf "add table inet %s\n" "$name_program"                                                                            >> "$fpath_ruleset.tmp"
+			printf "flush table inet %s\n" "$name_program"                                                                          >> "$fpath_ruleset.tmp"
+			printf "add chain inet %s %s { type filter hook output priority 0 ; policy accept; }\n" "$name_program" "$name_program" >> "$fpath_ruleset.tmp"
 
 			# Perform WHOIS Query of ASN(s) for Prefixes:
 
@@ -145,17 +145,17 @@ main()
 
 			if ! [ -z "$list_prefixes_ipv4" ]
 			then
-				printf "$list_prefixes_ipv4\n" | while IFS= read -r prefix
+				printf "%s\n" "$list_prefixes_ipv4" | while IFS= read -r prefix
 				do
-					printf "add rule inet $name_program $name_program ip daddr $prefix reject\n" >> "$fpath_ruleset.tmp"
+					printf "add rule inet %s %s ip daddr %s reject\n" "$name_program" "$name_program" "$prefix" >> "$fpath_ruleset.tmp"
 				done
 			fi
 
 			if ! [ -z "$list_prefixes_ipv6" ]
 			then
-				printf "$list_prefixes_ipv6\n" | while IFS= read -r prefix
+				printf "%s\n" "$list_prefixes_ipv6" | while IFS= read -r prefix
 				do
-					printf "add rule inet $name_program $name_program ip6 daddr $prefix reject\n" >> "$fpath_ruleset.tmp"
+					printf "add rule inet %s %s ip6 daddr %s reject\n" "$name_program" "$name_program" "$prefix" >> "$fpath_ruleset.tmp"
 				done
 			fi
 
@@ -219,7 +219,7 @@ confirm_asn()
 	whoisdomain="$1"
 	list_asn="$2"
 
-	printf "$list_asn\n" | while IFS= read -r asn
+	printf "%s\n" "$list_asn" | while IFS= read -r asn
 	do
 		if ! whois -h "$whoisdomain" -- -i origin "$asn" | grep -Eq '^route\:'
 		then
@@ -307,7 +307,7 @@ confirm_root_access()
 {
 	if [ "$(id -u)" != 0 ]
 	then
-		>&2 printf "> error: $(basename "$0") not running as root.\n"
+		>&2 printf "> error: %s not running as root.\n" "$(basename "$0")"
 		return 2
 	fi
 }
@@ -317,7 +317,7 @@ print_prefixes_ipv4()
 	whoisdomain="$1"
 	list_asn="$2"
 
-	printf "$list_asn\n" | while IFS= read -r asn
+	printf "%s\n" "$list_asn" | while IFS= read -r asn
 	do
 		whois -h "$whoisdomain" -- -i origin "$asn" | awk '/route:/ {print $2}'
 	done
@@ -328,7 +328,7 @@ print_prefixes_ipv6()
 	whoisdomain="$1"
 	list_asn="$2"
 
-	printf "$list_asn\n" | while IFS= read -r asn
+	printf "%s\n" "$list_asn" | while IFS= read -r asn
 	do
 		whois -h "$whoisdomain" -- -i origin "$asn" | awk '/route6:/ {print $2}'
 	done
